version: '3.8'
services:
  concrescent:
    build:
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - "80:8080"
    user: nobody
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./cm2:/var/www/html:ro
      - ./vendor:/var/www/vendor:ro
      - ./templates:/var/www/templates:ro
      - ./msmtprc:/etc/msmtprc:ro
      - ./concrescent.php:/srv/host/config.php:ro
    env_file:
      - .env.dev
      - .env
  mysql:
    image: mysql:8.2
    restart: unless-stopped
    ports:
    - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./var/mysql-data:/var/lib/mysql
    env_file:
    - .env.dev
    - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 5s
